name: Release
run-name: '📦 Release: ${{ github.event.head_commit.message || github.event.pull_request.title }}'

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  packages: write
  pull-requests: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install Dependencies
        run: npm ci

      - name: Publish/Version Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
